'use strict';

// Copied from https://facebook.github.io/react/docs/dom-elements.html
// Copied from https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#Attribute_list
var map ={
  "accept": "accept",
  "accept-charset": "acceptCharset",
  "accesskey": "accessKey",
  "action": "action",
  "alt": "alt",
  "async": "async",
  "autocomplete": "autoComplete",
  "autofocus": "autoFocus",
  "autoplay": "autoPlay",
  "challenge": "challenge",
  "charset": "charSet",
  "checked": "checked",
  "cite": "cite",
  "class": "className",
  "cols": "cols",
  "colspan": "colSpan",
  "content": "content",
  "contenteditable": "contentEditable",
  "contextmenu": "contextMenu",
  "controls": "controls",
  "coords": "coords",
  "crossorigin": "crossOrigin",
  "data": "data",
  "datetime": "dateTime",
  "default": "default",
  "defer": "defer",
  "dir": "dir",
  "disabled": "disabled",
  "download": "download",
  "draggable": "draggable",
  "enctype": "encType",
  "for": "htmlFor",
  "form": "form",
  "formaction": "formAction",
  "headers": "headers",
  "height": "height",
  "hidden": "hidden",
  "high": "high",
  "href": "href",
  "hreflang": "hrefLang",
  "http-equiv": "httpEquiv",
  "icon": "icon",
  "id": "id",
  "integrity": "integrity",
  "keytype": "keyType",
  "kind": "kind",
  "label": "label",
  "lang": "lang",
  "list": "list",
  "loop": "loop",
  "low": "low",
  "manifest": "manifest",
  "max": "max",
  "maxlength": "maxLength",
  "minlength": "minLength",
  "media": "media",
  "method": "method",
  "min": "min",
  "multiple": "multiple",
  "muted": "muted",
  "name": "name",
  "novalidate": "noValidate",
  "open": "open",
  "optimum": "optimum",
  "pattern": "pattern",
  "placeholder": "placeholder",
  "poster": "poster",
  "preload": "preload",
  "radiogroup": "radioGroup",
  "readonly": "readOnly",
  "rel": "rel",
  "required": "required",
  "reversed": "reversed",
  "rows": "rows",
  "rowspan": "rowSpan",
  "sandbox": "sandbox",
  "scope": "scope",
  "scoped": "scoped",
  "selected": "selected",
  "shape": "shape",
  "size": "size",
  "sizes": "sizes",
  "span": "span",
  "spellcheck": "spellCheck",
  "src": "src",
  "srcdoc": "srcDoc",
  "srclang": "srcLang",
  "srcset": "srcSet",
  "start": "start",
  "step": "step",
  "style": "style",
  "summary": "summary",
  "tabindex": "tabIndex",
  "target": "target",
  "title": "title",
  "type": "type",
  "usemap": "useMap",
  "value": "value",
  "width": "width",
  "wrap": "wrap"
};

var convert = function (attr) {
  return map[key] || attr;
};

module.exports = convert;
module.exports.convert = convert;
